module.exports = {
  env: {
    node: true
  },

  rules: {
    // Possible errors
    'comma-dangle': 2,
    'no-cond-assign': 2,
    'no-console': 2,
    'no-constant-condition': 2,
    'no-control-regex': 2,
    'no-debugger': 2,
    'no-dupe-args': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-empty-character-class': 2,
    'no-empty': 2,
    'no-ex-assign': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-parens': 0,
    'no-extra-semi': 2,
    'no-func-assign': 2,
    'no-inner-declarations': 2,
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-negated-in-lhs': 2,
    'no-obj-calls': 2,
    'no-regex-spaces': 2,
    'no-sparse-arrays': 2,
    'no-unreachable': 2,
    'use-isnan': 2,
    'valid-jsdoc': [1, {
        requireParamDescription: false,
        requireReturnDescription: false,
        requireReturn: false
    }],
    'valid-typeof': 2,
    'no-unexpected-multiline': 2,

    // Enforce
    'accessor-pairs': 1,
    'block-scoped-var': 2,
    'complexity': 1,
    'consistent-return': 0,
    'curly': 0,
    'default-case': 2,
    'dot-notation': 2,
    'dot-location': [2, 'property'],
    'eqeqeq': 2,
    'guard-for-in': 2,
    'no-alert': 2,
    'no-caller': 2,
    'no-div-regex': 2,
    'no-else-return': 2,
    'no-empty-label': 2,
    'no-eq-null': 2,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-fallthrough': 2,
    'no-floating-decimal': 2,
    'no-implicit-coercion': 1,
    'no-implied-eval': 2,
    'no-invalid-this': 0,
    'no-iterator': 2,
    'no-labels': 2,
    'no-lone-blocks': 2,
    'no-loop-func': 2,
    'no-multi-spaces': 2,
    'no-multi-str': 2,
    'no-native-reassign': 2,
    'no-new-func': 2,
    'no-new-wrappers': 2,
    'no-new': 2,
    'no-octal-escape': 2,
    'no-octal': 2,
    'no-param-reassign': 0,
    'no-process-env': 1,
    'no-proto': 2,
    'no-redeclare': 2,
    'no-return-assign': 2,
    'no-script-url': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-throw-literal': 2,
    'no-unused-expressions': 2,
    'no-useless-call': 2,
    'no-void': 2,
    'no-warning-comments': 2,
    'no-with': 2,
    'radix': 2,
    'vars-on-top': 0,
    'wrap-iife': 0,
    'yoda': [1, 'never', {onlyEquality: true}],

    // Strict
    'strict': [2, 'global'],

    // Variables
    'init-declarations': 0,
    'no-catch-shadow': 2,
    'no-delete-var': 2,
    'no-label-var': 2,
    'no-shadow-restricted-names': 2,
    'no-shadow': 2,
    'no-undef-init': 2,
    'no-undef': 2,
    'no-undefined': 2,
    'no-unused-vars': 2,
    'no-use-before-define': 2,

    // Node.js
    'callback-return': 0,
    'handle-callback-err': 2,
    'no-mixed-requires': 2,
    'no-new-require': 2,
    'no-path-concat': 0,
    'no-process-exit': 2,
    'no-restricted-modules': 0,
    'no-sync': 0,

    // Stylistic Issues
    'array-bracket-spacing': [1, 'never'],
    'brace-style': 0,
    'camelcase': 0,
    'comma-spacing': 1,
    'comma-style': 1,
    'computed-property-spacing': 1,
    'consistent-this': 0,
    'eol-last': 1,
    'func-names': 0,
    'func-style': [1, 'expression'],
    'id-length': 0,
    'id-match': 0,
    'indent': 0,
    'key-spacing': 1,
    'lines-around-comment': 0,
    'linebreak-style': [1, 'unix'],
    'max-nested-callbacks': 0,
    'new-cap': 1,
    'new-parens': 0,
    'newline-after-var': 0,
    'no-array-constructor': 1,
    'no-continue': 1,
    'no-inline-comments': 1,
    'no-lonely-if': 0,
    'no-mixed-spaces-and-tabs': 1,
    'no-multiple-empty-lines': 0,
    'no-nested-ternary': 1,
    'no-new-object': 1,
    'no-spaced-func': 1,
    'no-ternary': 0,
    'no-trailing-spaces': 1,
    'no-underscore-dangle': 0,
    'no-unneeded-ternary': 1,
    'object-curly-spacing': 0,
    'one-var': 0,
    'operator-assignment': [1, 'always'],
    'operator-linebreak': 0,
    'padded-blocks': [1, 'never'],
    'quote-props': [1, 'as-needed'],
    'quotes': [1, 'single'],
    'semi-spacing': 1,
    'semi': 1,
    'sort-vars': 0,
    'space-after-keywords': 0,
    'space-before-blocks': 0,
    'space-before-function-paren': 0,
    'space-in-parens': 1,
    'space-infix-ops': 1,
    'space-return-throw-case': 1,
    'space-unary-ops': 1,
    'spaced-comment': 0,
    'wrap-regex': 0,

    // ECMAScript 6
    'arrow-parens': [1, 'as-needed'],
    'arrow-spacing': 1,
    'constructor-super': 2,
    'generator-star-spacing': 1,
    'no-class-assign': 2,
    'no-const-assign': 2,
    'no-this-before-super': 2,
    'no-var': 0,
    'object-shorthand': 0,
    'prefer-const': 0,
    'prefer-spread': 0,
    'prefer-reflect': 0,
    'require-yield': 2
  }
};
